accounts:
  # Account 1: Relevance Lab (Management)
  - name: Relevance_Lab
    id: 549974527830
    email: devops.support@relevancelab.com
    organizationalUnit: Root

  # Account 2: RES-DEMO
  - name: RES_DEMO
    id: 881490115770
    email: res.testing@relevancelab.com
    organizationalUnit: Root
