mandatoryAccounts:
  - name: Management
    description: The management (primary) account.
    email: devops.support@relevancelab.com
    organizationalUnit: Root
  - name: LogArchive
    description: The log archive account.
    email: logawsct2@relevancelab.com
    organizationalUnit: Security
  - name: Audit
    description: The security audit account.
    email: auditawsct2@relevancelab.com
    organizationalUnit: Security

workloadAccounts:
  - name: RES-DEMO
    description: RES-DEMO account
    email: res.testing@relevancelab.com
    organizationalUnit: RES
  - name: RLCatalystProd
    description: RLCatalyst Production account
    email: rlcatalystprod@relevancelab.com
    organizationalUnit: RLRGProd
  - name: RLCatalyst_NonProd
    description: RLCatalyst Non-Production account
    email: neoresearch@relevancelab.com
    organizationalUnit: RLRG_QA
  - name: RG_Testing
    description: RG Testing account
    email: rgtest@relevancelab.com
    organizationalUnit: RLRG_QA
  - name: SCHL-Project-Workspaces
    description: SCHL Project Workspaces account
    email: schlworkspaces@relevancelab.com
    organizationalUnit: SCHL
  - name: RLDevOpsIndia
    description: RL DevOps India account
    email: rldevopsindia@relevancelab.com
    organizationalUnit: Devops
  - name: Data_Team
    description: Data Team account
    email: rlserviceone19@relevancelab.com
    organizationalUnit: Data_Team
