enable: true
organizationalUnits:
  - name: RLRGProd
  - name: Security
  - name: Devops
  - name: RES
  - name: RLRG_QA
  - name: Data_Team
  - name: Infrastructure
  - name: SCHL
serviceControlPolicies: []
taggingPolicies: []
backupPolicies: []
